### ISSUE TITLE
Scroll bar color

### ISSUE THREAD

**Issue by i007c** [juxtopposed/realtimecolors#5]
it would be cool to match the scroll bar colors with the color palette.

**Comment by juxtopposed** [comment]
Interesting... Which colors exactly are you thinking?

**Comment by i007c** [comment]
im talking about `::-webkit-scrollbar` prop in css.
the sites scroll bar is just white and doesn't change.

**Comment by juxtopposed** [comment]
What color(s) from the palette are you thinking of setting that for?

**Comment by i007c** [comment]
ahhh. understood what you meant now.
idk any thing is better then the default white color.

```css
::-webkit-scrollbar {
    background: var(--secondary);
}

::-webkit-scrollbar-thumb {
    background: var(--primbuttn);
}
```
im not a designer but this is ok :)
